### ISSUE TITLE
题库已经全部更新了。

### ISSUE THREAD

**Issue by hyy34** [kessil/AutoXue#121]
试了好多次，没有一道题，大家题库都去哪能弄到？

**Comment by cedar-c** [comment]
你是什么版本的？

**Comment by hyy34** [comment]
> 你是什么版本的？

不分版本啊，我是说挑战的题库。

**Comment by cedar-c** [comment]
> > 你是什么版本的？
> 
> 不分版本啊，我是说挑战的题库。

我的今天突然失效了。所以才问问，想求一个
794211584@qq.com

**Comment by hyy34** [comment]
> > > 你是什么版本的？
> > 
> > 
> > 不分版本啊，我是说挑战的题库。
> 
> 我的今天突然失效了。所以才问问，想求一个
> [794211584@qq.com](mailto:794211584@qq.com)

自从2.0后就没用过了，都是手动，但是没有题库，挑战太难了。

**Comment by ipez** [comment]
现在不需要更新题库了，大部分新题目都是每日答题跟专项答题里的，并且每天刷新的题目顺序是固定的，多重复做几次就可以了。

**Comment by hyy34** [comment]
> 现在不需要更新题库了，大部分新题目都是每日答题跟专项答题里的，并且每天刷新的题目顺序是固定的，多重复做几次就可以了。

我是手动答题，需要挑战答题的答案。现在题目全换了，所以答案参考不上了。但是2次机会打10道题也挺难。

**Comment by wmm1118** [comment]
有大佬能发一下最后一个版本的程序么？wmm1118@qq.com

**Comment by cedar-c** [comment]
> 有大佬能发一下最后一个版本的程序么？[wmm1118@qq.com](mailto:wmm1118@qq.com)

我也想要

**Comment by ipez** [comment]
> > 现在不需要更新题库了，大部分新题目都是每日答题跟专项答题里的，并且每天刷新的题目顺序是固定的，多重复做几次就可以了。
> 
> 我是手动答题，需要挑战答题的答案。现在题目全换了，所以答案参考不上了。但是2次机会打10道题也挺难。

不止两次机会，答错了直接返回就可以了，不算次数，不要点击完成本局。

**Comment by td-date** [comment]
https://github.com/kessil/AutoXue/issues/32#issuecomment-545224080

**Comment by hyy34** [comment]
> [#32 (comment)](https://github.com/kessil/AutoXue/issues/32#issuecomment-545224080)
> 新题。

刚才试了下，10道能错了8道吧。

**Comment by td-date** [comment]
题库，解压后放\xuexi\目录下。
[data-dev.zip](https://github.com/kessil/AutoXue/files/3776891/data-dev.zip)

**Comment by kessil** [comment]
要不，试用一下船新版本？

**Comment by cedar-c** [comment]
船新版本没有功能介绍，是和之前的一样能得41分吗？

**Comment by hyy34** [comment]
> 要不，试用一下船新版本？

想要个单独的题库。在哪里？

**Comment by kessil** [comment]
> 
> 
> > 要不，试用一下船新版本？
> 
> 感觉安装好难啊，出个视频被。。或者只要个单独的题库就可。在哪下载呢？

只要题库，请移步[https://github.com/kessil/flaskr](https://github.com/kessil/flaskr)
