### ISSUE TITLE
请问挑战答题每次的答题目标数如何修改范围？

### ISSUE THREAD

**Issue by programmerZe** [kessil/AutoXue#126]
`class CONST:
    CHALLENGE_COUNT_MIN = 20
    CHALLENGE_COUNT_MAX = 40
    CHALLENGE_DELAY_MIN = 1
    CHALLENGE_DELAY_MAX = 8`
是这部分代码吗？

**Comment by kessil** [comment]
是的，随机值的上下限

**Comment by programmerZe** [comment]
好的，谢谢
