### ISSUE TITLE
请问作者是如何获取“学习积分”界面的内容？

### ISSUE THREAD

**Issue by Meteoooor** [kessil/AutoXue#129]
其余界面都可以用ADB  shell uiautomator dump 获取，而且好像您也是使用了这种方式，唯独之前最后一次更新时，更新了在“学习积分”界面直接获取学习进度，且在SD卡目录下的UI.xml发现您可以获取到学习进度的内容，这是使用了什么命令或者什么方式？

**Comment by kessil** [comment]
使用`ADB shell uiautomator dump`在mumu模拟器下能获取到完整的ui.xml，在其他设备或模拟器上取不到，这应该是网易团队的黑科技吧。

**Comment by Meteoooor** [comment]
> 使用`ADB shell uiautomator dump`在mumu模拟器下能获取到完整的ui.xml，在其他设备或模拟器上取不到，这应该是网易团队的黑科技吧。

真是奇怪。。我使用MuMu也能获取到，万分感谢
