### ISSUE TITLE
挑战答题有没有更新渠道，目前好多题目题库上已没有了

### ISSUE THREAD

**Issue by zhuohui** [kessil/AutoXue#133]

**Comment by AmosYjl** [comment]
求联系方式

**Comment by td-date** [comment]
解压放xuexi目录.
[4075题data-dev.zip](https://github.com/kessil/AutoXue/files/3877763/4075.data-dev.zip)

**Comment by erebusx** [comment]
感谢楼上的，挑战答题没有自动记录答案，不能自动更新，是个遗憾，现在上新版本了，老版本只能凑合用不会增加功能了吧

**Comment by kessil** [comment]
quizXue没有接入最新的题库接口，而且题库结构有些许变化，两者不通用。目前维护AutoXue
