### ISSUE TITLE
请问作者：每日答题的填空题具体操作流程是什么样的？

### ISSUE THREAD

**Issue by Meteoooor** [kessil/AutoXue#135]
我的流程是 首先获取填空题第一个空格的bounds，然后用模拟点击去点击一下第一个空格，然后用adb shell am broadcast -a ADB_INPUT_TEXT --es msg '答案’来提交答案，这样也能填空，可是会导致模拟器自己跳到前台激活，不模拟点击一下空格，填空题的答案又填不进去。求教
![微信图片_20191122083740](https://user-images.githubusercontent.com/33692045/69388330-73f94380-0d03-11ea-8c22-b93765d65459.png)
![微信图片_20191122083800](https://user-images.githubusercontent.com/33692045/69388331-73f94380-0d03-11ea-8713-365605760207.png)

**Comment by Meteoooor** [comment]
模拟点击是使用的 adb shell input tap X坐标  Y坐标

**Comment by kessil** [comment]
就是这个流程，记得不会激活呀。你的再来一组提示有意思
