### ISSUE TITLE
学习过程中总是会404，然后就结束了

### ISSUE THREAD

**Issue by extranquil** [kessil/AutoXue#188]
appium log：

[W3C (d0512804)] Calling AppiumDriver.findElement() with args: ["id","cn.xuexi.android:id/st_feeds_card_mask_pic_num","d0512804-ba1f-45ec-9015-fc134a9cd843"]
[BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
[BaseDriver] Waiting up to 0 ms for condition
[WD Proxy] Matched '/element' to command name 'findElement'
[WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/904d3f01-6697-4641-9f74-4b4fcd42c466/element] with body: {"strategy":"id","selector":"cn.xuexi.android:id/st_feeds_card_mask_pic_num","context":"","multiple":false}
[WD Proxy] Got an unexpected response with status 404: {"sessionId":"904d3f01-6697-4641-9f74-4b4fcd42c466","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:78)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
[W3C] Matched W3C error code 'no such element' to NoSuchElementError
[W3C (d0512804)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
[W3C (d0512804)]     at AndroidUiautomator2Driver.findElOrEls (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:75:11)
[HTTP] <-- POST /wd/hub/session/d0512804-ba1f-45ec-9015-fc134a9cd843/element 404 242 ms - 421
[HTTP] 
[HTTP] --> POST /wd/hub/session/d0512804-ba1f-45ec-9015-fc134a9cd843/element/91dce71d-54f2-4877-b9ef-07a4b4957780/click
[HTTP] {"id":"91dce71d-54f2-4877-b9ef-07a4b4957780"}

**Comment by kessil** [comment]
> 
> 
> appium log：
> 
> [W3C (d0512804)] Calling AppiumDriver.findElement() with args: ["id","cn.xuexi.android:id/st_feeds_card_mask_pic_num","d0512804-ba1f-45ec-9015-fc134a9cd843"]
> [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
> [BaseDriver] Waiting up to 0 ms for condition
> [WD Proxy] Matched '/element' to command name 'findElement'
> [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/904d3f01-6697-4641-9f74-4b4fcd42c466/element] with body: {"strategy":"id","selector":"cn.xuexi.android:id/st_feeds_card_mask_pic_num","context":"","multiple":false}
> [WD Proxy] Got an unexpected response with status 404: {"sessionId":"904d3f01-6697-4641-9f74-4b4fcd42c466","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:78)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
> [W3C] Matched W3C error code 'no such element' to NoSuchElementError
> [W3C (d0512804)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
> [W3C (d0512804)] at AndroidUiautomator2Driver.findElOrEls (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:75:11)
> [HTTP] <-- POST /wd/hub/session/d0512804-ba1f-45ec-9015-fc134a9cd843/element 404 242 ms - 421
> [HTTP]
> [HTTP] --> POST /wd/hub/session/d0512804-ba1f-45ec-9015-fc134a9cd843/element/91dce71d-54f2-4877-b9ef-07a4b4957780/click
> [HTTP] {"id":"91dce71d-54f2-4877-b9ef-07a4b4957780"}

An element could not be located on the page using the given search parameters

**Comment by extranquil** [comment]
> > appium log：
> > [W3C (d0512804)] Calling AppiumDriver.findElement() with args: ["id","cn.xuexi.android:id/st_feeds_card_mask_pic_num","d0512804-ba1f-45ec-9015-fc134a9cd843"]
> > [BaseDriver] Valid locator strategies for this request: xpath, id, class name, accessibility id, -android uiautomator
> > [BaseDriver] Waiting up to 0 ms for condition
> > [WD Proxy] Matched '/element' to command name 'findElement'
> > [WD Proxy] Proxying [POST /element] to [POST http://localhost:8200/wd/hub/session/904d3f01-6697-4641-9f74-4b4fcd42c466/element] with body: {"strategy":"id","selector":"cn.xuexi.android:id/st_feeds_card_mask_pic_num","context":"","multiple":false}
> > [WD Proxy] Got an unexpected response with status 404: {"sessionId":"904d3f01-6697-4641-9f74-4b4fcd42c466","value":{"error":"no such element","message":"An element could not be located on the page using the given search parameters","stacktrace":"io.appium.uiautomator2.common.exceptions.ElementNotFoundException: An element could not be located on the page using the given search parameters\n\tat io.appium.uiautomator2.handler.FindElement.safeHandle(FindElement.java:78)\n\tat io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:38)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:252)\n\tat io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:242)\n\tat io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:44)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)\n\tat io.netty.chann...
> > [W3C] Matched W3C error code 'no such element' to NoSuchElementError
> > [W3C (d0512804)] Encountered internal error running command: NoSuchElementError: An element could not be located on the page using the given search parameters.
> > [W3C (d0512804)] at AndroidUiautomator2Driver.findElOrEls (C:\Program Files\Appium\resources\app\node_modules\appium\node_modules\appium-android-driver\lib\commands\find.js:75:11)
> > [HTTP] <-- POST /wd/hub/session/d0512804-ba1f-45ec-9015-fc134a9cd843/element 404 242 ms - 421
> > [HTTP]
> > [HTTP] --> POST /wd/hub/session/d0512804-ba1f-45ec-9015-fc134a9cd843/element/91dce71d-54f2-4877-b9ef-07a4b4957780/click
> > [HTTP] {"id":"91dce71d-54f2-4877-b9ef-07a4b4957780"}
> 
> An element could not be located on the page using the given search parameters

页面没刷出来导致的？求教如何给findelement加延时？

**Comment by kessil** [comment]
## 一般有两种情况：
+ 使用self.wait定位元素，超时设置再父类中定义如下：

![捕获](https://user-images.githubusercontent.com/11907802/76698148-73cdeb00-66da-11ea-8039-e3a79c98cb60.PNG)

+ 使用self.driver.find... 直接再上一行加入或修改time.sleep(N) N 为秒数

**Comment by extranquil** [comment]
> ## 一般有两种情况：
> * 使用self.wait定位元素，超时设置在父类中定义如下：
> 
> ![捕获](https://user-images.githubusercontent.com/11907802/76698148-73cdeb00-66da-11ea-8039-e3a79c98cb60.PNG)
> 
> * 使用self.driver.find... 直接再上一行加入或修改time.sleep(N) N 为秒数

明白，太感谢了！
