### ISSUE TITLE
最新更新的好像有问题，不知道是不是个例，请看照片。

### ISSUE THREAD

**Issue by LINGJULIDEHUIMOU** [kessil/AutoXue#189]
![QQ图片20200316014232](https://user-images.githubusercontent.com/54373657/76707097-773b9380-6727-11ea-9c32-2cd69d761853.png)

**Comment by StraightJet** [comment]
打开`xuexi`文件夹下的`__main__.py`文件，拉到最下边。
把
```
if __name__ == "__main__":
    #start()
    test()
```
修改为
```
if __name__ == "__main__":
    start()
    #test()
```

**Comment by kessil** [comment]
已修复此错误
