### ISSUE TITLE
syntax错误！

### ISSUE THREAD

**Issue by zz803abc** [kessil/AutoXue#20]
![image](https://user-images.githubusercontent.com/50546321/62007750-ea39cf00-b183-11e9-9eef-28d6edd0cb90.png)
是不是哪里的空格或缩进不对？？

**Comment by zz803abc** [comment]
![image](https://user-images.githubusercontent.com/50546321/62007834-dd69ab00-b184-11e9-996a-1a21348e3c42.png)

python3的话是找不到playsound模块，怎么办？？

**Comment by kessil** [comment]
pip install playsound
