### ISSUE TITLE
在真机上使用出了问题

### ISSUE THREAD

**Issue by JianChi8** [kessil/AutoXue#211]
我在真机上试用了一下，出了问题

我的手机：MI_5s
刷机 lineageos
开启了 网络调试

我修改了default.ini中的
platformversion = 9
uuid = 我的手机

adb连接没问题，脚本自动启动了APP，并自动跳转到了得分页面

但在这一句出了问题
        score_list = self.wait.until(EC.presence_of_all_elements_located((By.XPATH, rules['score_list'])))

一直无法返回数据，最后显示超时

我使用记夜神模拟器使用没问题的

**Comment by JianChi8** [comment]
问题应该出在uc webview上，阿里系的APP都使用的是uc webview。
在夜神上，没有安装其它阿里系的APP，或者是因为安卓版本过低等原因，学习强国使用的是系统自带的webkit，所以可以抓到内容。但手机上使用提uc webview，appium抓不到它的内容，这就出问题了。

**Comment by kessil** [comment]
真机上确实存在这个问题

**Comment by extranquil** [comment]
MuMu模拟器也抓不到数据

**Comment by kessil** [comment]
具体哪个模拟器哪个安卓版本能获取xml数据还需自行多尝试一下，作者没有覆盖所有版本
