### ISSUE TITLE
API不堪重负request faild

### ISSUE THREAD

**Issue by tmp-bzlufdvbsuvn** [kessil/AutoXue#213]
最近答题类用到API时总会request faild
- 可能是不堪重负了
- 或者考虑限制一下恶意访问

**Comment by AlgorithmKevin** [comment]
我从昨天开始也连接不到服务器了，API停掉了吗？还是服务器不堪重负了？

**Comment by kessil** [comment]
可能服务挂了。这段时间发现api确实存在一些问题，新添加了许多填空题不带空格，但是查了 autoxue 是能正确获取到填空题空格的，另一个就是云主机属入门级的(捂脸)。

**Comment by kessil** [comment]
放在云主机上又有大量脏数据，想写一个本地的api服务，大家可以自己本地起题库，不过嘛，无法享受共享题库的便利。大家如果有更好的建议可以提出来，感觉加权限控制还是没办法避免脏数据，毕竟这是开源的，修改源码太自由了，要破解权限也很轻松

**Comment by Https443** [comment]
有劳大佬了，如果课自己本地起题库那再好不过了

**Comment by tasagapro** [comment]
本地题库等做成一个docker镜像，就很方便了

**Comment by githubnew007** [comment]
> 可能服务挂了。这段时间发现api确实存在一些问题，新添加了许多填空题不带空格，但是查了 autoxue 是能正确获取到填空题空格的，另一个就是云主机属入门级的(捂脸)。
------------------有劳大佬，服务又挂了-----
502 Bad Gateway nginx/1.14.0 (Ubuntu)

**Comment by githubnew007** [comment]
感谢kessil大佬，题库API服务正常了

**Comment by kessil** [comment]
云主机挂了，重启了恢复，感谢大家的关注
