### ISSUE TITLE
老哥，之前的都弄好了，就是到了这里就自动停了，求您指点，拜谢老哥.[INFO] 每日答题 第 5# 组 [ERROR] 无法获取题目类型

### ISSUE THREAD

**Issue by shajia1992** [kessil/AutoXue#217]
![image](https://user-images.githubusercontent.com/34378388/83167960-5ccc6000-a143-11ea-85c2-8aa36e8e963a.png)

**Comment by shajia1992** [comment]
![image](https://user-images.githubusercontent.com/34378388/83168774-98b3f500-a144-11ea-88ba-965dfa8b4bf8.png)

**Comment by kessil** [comment]
模拟器卡顿造成。我将关闭这个issue，若有其他问题请追问。
