### ISSUE TITLE
积分改版，需更新

### ISSUE THREAD

**Issue by GOOD-AN** [kessil/AutoXue#234]
积分改版，无法检测到挑战答题未完成

**Comment by solife2020** [comment]
的确需要更新了，现在完全没法正常使用了，积分发生了变化，，文章变成了：我要选读文章；每日答题 是5道为6分；发表观点无法使用，本地频道无法使用。

**Comment by JacquesVonHamsterviel** [comment]
xuexi/__init__.py    747行 阅读文章 改成 我要选读文章

![1](https://user-images.githubusercontent.com/59958130/90258602-611f3400-de7b-11ea-8cee-2d3f694a0f23.PNG)
![2](https://user-images.githubusercontent.com/59958130/90258606-62e8f780-de7b-11ea-80a2-f5f766e13ffd.PNG)
![3](https://user-images.githubusercontent.com/59958130/90258618-65e3e800-de7b-11ea-8ec4-ba21f4b1dfc4.PNG)

**Comment by solife2020** [comment]
每日答题和挑战答题错误怎么解决呢?

**Comment by JacquesVonHamsterviel** [comment]
那个好像没有坏

**Comment by solife2020** [comment]
> 那个好像没有坏

分享一个你正在用的压缩包吖，我这里怎么弄都出错。哎。

**Comment by JacquesVonHamsterviel** [comment]
[core.zip](https://github.com/kessil/AutoXue/files/5078450/core.zip)
那个bat你需要自己改下，特别是最后几行。

**Comment by solife2020** [comment]
谢谢

**Comment by solife2020** [comment]
![QQ截图20200815183320](https://user-images.githubusercontent.com/60801692/90310627-e3643280-df25-11ea-8db4-fad06e080242.jpg)
tian填空类型的题目会出错。

**Comment by JacquesVonHamsterviel** [comment]
那我就不知道了，我暂时没这个问题。。。

**Comment by solife2020** [comment]
![QQ截图20200816073530](https://user-images.githubusercontent.com/60801692/90323380-1e507f80-df93-11ea-9249-40a40dfec95c.jpg)
看来是无法检测到挑战答题已经完成了，一直在重复做挑战答题。

**Comment by JacquesVonHamsterviel** [comment]
![40](https://user-images.githubusercontent.com/59958130/90324370-7b066700-dfa0-11ea-82b2-c262f65afc70.PNG)
你看这是它这么循环学习的结果，你让它在你睡觉的时候学习一个小时多一点，就能到达这个效果，至于中间的错误就不要管了。。。

![231](https://user-images.githubusercontent.com/59958130/90324389-de909480-dfa0-11ea-947e-40d47d7a6ed2.PNG)

**Comment by solife2020** [comment]
好的，谢谢，经过测试的确可以，希望以后更新的时候也能收到您的更新。

**Comment by stillhill** [comment]
> 
> 
> ![QQ截图20200815183740](https://user-images.githubusercontent.com/60801692/90310688-700ef080-df26-11ea-8b90-62c1cbb89963.jpg)
> ![QQ截图20200815183320](https://user-images.githubusercontent.com/60801692/90310627-e3643280-df25-11ea-8db4-fad06e080242.jpg)
> tian填空类型的题目会出错。

你好，我也碰到了一样的问题，请问你解决了吗？

**Comment by cedar-c** [comment]
> xuexi/**init**.py 747行 阅读文章 改成 我要选读文章
> 
> ![1](https://user-images.githubusercontent.com/59958130/90258602-611f3400-de7b-11ea-8cee-2d3f694a0f23.PNG)
> ![2](https://user-images.githubusercontent.com/59958130/90258606-62e8f780-de7b-11ea-80a2-f5f766e13ffd.PNG)
> ![3](https://user-images.githubusercontent.com/59958130/90258618-65e3e800-de7b-11ea-8ec4-ba21f4b1dfc4.PNG)

补充一下，因为现在收藏不加分了。所以可以直接把这一部分的给注释了，当然不管它也无所谓
![image](https://user-images.githubusercontent.com/54062513/90349709-562bf580-e06d-11ea-8f24-35e826a87251.png)

**Comment by tasagapro** [comment]
> [core.zip](https://github.com/kessil/AutoXue/files/5078450/core.zip)
> 那个cmd你需要自己改下，特别是最后几行。
> 
> 以下脚本加上wol唤醒可以实现 自定义时间自动开机学习然后关机。不过路径需要更改。还有学习结束有个消息推送，App Store里有个 Bark的软件，红色图标，那个可以实现。curl+推送的url。
> [s.zip](https://github.com/kessil/AutoXue/files/5078468/s.zip)

谢谢！您能否把代码直接上传到github，供我们克隆克隆-_-

**Comment by yangzuoming** [comment]
> > WOL推荐一下，因为就不需要你去开机了（在你睡觉的时候），而且可以设定开机时间（每天都不一样）。
> > 如果你用BIOS里面的定时开机，每天的时间都只能设定一样的吧。。。还是开机周期一样。。。
> > 1.比较建议用路由器实现， 因为之前买过向日葵的开机棒，定时开机功能不大好用，开个一次第二天就开不了。而且还要安装向日葵的客户端。
> > 2.如果你用的是梅林，OpenWrt,老毛子的路由器固件，那应该都可以实现的。梅林用winscp进路由器jssf分区，添加定时任务即可。
> > 参考文章：[WOL，网络唤醒的几件事，定时自动唤醒、访问时自动唤醒](https://koolshare.cn/thread-115602-1-1.html)
> > [RT-AC68U定時网络唤醒](http://www.52asus.com/thread-1892-1-1.html)
> > [WOL Script Wake Up Your Webserver On Internet Traffic ](https://github.com/RMerl/asuswrt-merlin.ng/wiki/WOL-Script-Wake-Up-Your-Webserver-On-Internet-Traffic)
> > 3.内网Linux服务器参考这个：[CentOS/Debian/Ubuntu 使用网络启动 Wake On LAN 的最新方法](https://pc6a.com/1870.html)
> > [在Linux下通过Wake On LAN实现网络唤醒远程开机](https://blog.csdn.net/fullbug/article/details/53197132)
> > 4.我还试过用nas上的docker实现，没成功
> 
> 希望能加上我分享的题库，这样可以让他直接通关挑战答题。

开个分支吧，我这边也做了一些代码修改，可以支持多账户刷分，看看能不能共同在吧这个项目优化一下

**Comment by tonylemon** [comment]
我遇到的问题：“分享”和“发表观点”以前可以实现的，现在不可以。望指出可能出问题的地方，谢谢！

**Comment by Tcwxc** [comment]
但是挑战答题答案为None是为什么？题库里面是有这道题的

**Comment by tonylemon** [comment]
> ![QQ截图20200815183740](https://user-images.githubusercontent.com/60801692/90310688-700ef080-df26-11ea-8b90-62c1cbb89963.jpg)
> ![QQ截图20200815183320](https://user-images.githubusercontent.com/60801692/90310627-e3643280-df25-11ea-8db4-fad06e080242.jpg)
> tian填空类型的题目会出错。

似乎因为电脑上输入法答题时是英文状态，手动切换成中文输入状态试试
