### ISSUE TITLE
每日答题单选为什么只选择A，填空只有'0'

### ISSUE THREAD

**Issue by hushiyan01** [kessil/AutoXue#27]
![image](https://user-images.githubusercontent.com/47495160/62419083-eab5f680-b6aa-11e9-91ca-cc81c32684ae.png)

**Comment by hushiyan01** [comment]
![image](https://user-images.githubusercontent.com/47495160/62419088-19cc6800-b6ab-11e9-9205-0596df4c5405.png)

**Comment by kessil** [comment]
为了验证想法而简单实现的功能，所以对于答案并没有做过多处理，下一个版本在这方面有所改进，正在重构中，感谢支持。

**Comment by kessil** [comment]
新分支dev完善了每日答题题库，正确率80%，欢迎刷题扩充题库，请依readme安装Adbboardkey
