### ISSUE TITLE
又出现新错误

### ISSUE THREAD

**Issue by cedar-c** [kessil/AutoXue#43]
Traceback (most recent call last):
  File "D:\python\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\python\lib\runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\python\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "F:\AutoXue-master\xuexi\__init__.py", line 25, in <module>
    cfg.read(path/'config-custom.ini', encoding='utf-8')
  File "D:\python\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "D:\python\lib\configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: WindowsPath('F:/AutoXue-master/xuexi/config-custom.ini'), line: 1
'\ufeff[common]\n'

不知道咋回事，本来好了，然后就这样了
另外大佬教的改端口还是不会，不知道加在哪里，求大佬

**Comment by kessil** [comment]
config-custom.ini应该长这个样子：
```
[mumu]
port = 5555
```
就可以了

**Comment by cedar-c** [comment]
> 配置-的custom.ini应该长这个样子：
> 
> ```
> [mumu]
> port = 5555
> ```
> 
> 就可以了

出现了上面的错误以后再次运行直接就这样了
是把[commom]改成[mumu] port = 5555吗？

**Comment by kessil** [comment]
> 
> 
> > 配置-的custom.ini应该长这个样子：
> > ```
> > [mumu]
> > port = 5555
> > ```
> > 
> > 
> > 就可以了
> 
> 出现了上面的错误以后再次运行直接就显示上面的错误了
> 
> 是把device = mumu改成[mumu] port = 5555吗？

请看./xuexi/config-custom.ini第36~53行

**Comment by cedar-c** [comment]
> > > 配置 - 的的custom.ini应该长这个样子：
> > > ```
> > > [mumu]
> > > port = 5555
> > > ```
> > > 
> > > 
> > > 就可以了
> > 
> > 
> > 出现了上面的错误以后再次运行直接就显示上面的错误了
> > 是把device = mumu改成[mumu] port = 5555吗？
> 
> 请看./xuexi/config-custom.ini第36〜53行

大佬，config-custom.ini只有25行，config-default.ini里面36~53才是模拟器端口设置，所以是不是在config-default.ini里面改啊，看大佬说要在custom里面改但是实在没找到啊
