### ISSUE TITLE
填空题选择题均答错

### ISSUE THREAD

**Issue by guoba321** [kessil/AutoXue#47]
填空题一律回复“不忘初心，牢记使命”，选择题有时可以答对，有时答错。

**Comment by K1two2** [comment]
每日答题和挑战答题全是试探性提交答案，难道更新题库了？

**Comment by kessil** [comment]
不好意思，昨天的custom数据库配置有误，重新拉取以一下谢谢

**Comment by LIUYUYANSZ** [comment]
昨天的custom数据库配置有误，重新拉取以一下谢谢
请问如何拉取

**Comment by guoba321** [comment]
> 昨天的custom数据库配置有误，重新拉取以一下谢谢
> 请问如何拉取

重新下载一次即可。

**Comment by guoba321** [comment]
非常感谢。
