### ISSUE TITLE
求教adb配置上的问题

### ISSUE THREAD

**Issue by qfzy1233** [kessil/AutoXue#75]
运行“开始积分”失败，报错信息如下：

* daemon not running; starting now at tcp:5037
adb: CreateProcessW failed: 系统找不到指定的文件。 (2)
* failed to start daemon
error: cannot connect to daemon

ADB版本为1.0.40

**Comment by ohhhyy** [comment]
adb.exe AdbWinApi.dll AdbWinUsbApi.dll 复制到C:\Windows\SysWOW64下

**Comment by qfzy1233** [comment]
已经解决了，自己运行一下  adb nodaemon server  然后正常运行程序就可以
