### ISSUE TITLE
【建议&BUG】答题时答案出错处理！

### ISSUE THREAD

**Issue by SoftPaper** [kessil/AutoXue#79]
挑战答题有时答案是错误的，然后APP就会跳转到结束本轮答题页面，CMD窗口就卡在此处不动了，这时应该怎么处理？ @kessil

**Comment by kessil** [comment]
出错了如果没达到指定题数应该会再挑战一轮，cmd卡住了试试回车有没有用。我发现powershell有时会因为鼠标点击或滑动而卡住，回车就继续执行了
