### ISSUE TITLE
【疑问】最新版的没有config-custom.ini.

### ISSUE THREAD

**Issue by SoftPaper** [kessil/AutoXue#84]
最新版的没有config-custom.ini文件，如果我要修改观看视频数量等项目是要在default里直接修改还是要总计创建一个custom文件？我先自己创建一个试试。

**Comment by kessil** [comment]
> 最新版的没有config-custom.ini文件，如果我要修改观看视频数量等项目是要在default里直接修改还是要总计创建一个custom文件？我先自己创建一个试试。

新建一个，注意文件名和utf-8编码

**Comment by SoftPaper** [comment]
> > 最新版的没有config-custom.ini文件，如果我要修改观看视频数量等项目是要在default里直接修改还是要总计创建一个custom文件？我先自己创建一个试试。
> 
> 新建一个，注意文件名和utf-8编码

好快！
