### ISSUE TITLE
能否考虑评论发表之后自动删除？

### ISSUE THREAD

**Issue by erebusx** [kessil/AutoXue#92]
评论的内容是随机的，自动删除是不是更好更安全，反正只要发表就有积分了，没必要留着。

**Comment by kessil** [comment]
```
[common]
; 是否保留留言和收藏
keep_star_comment = false
```

**Comment by lmaisui** [comment]
> ```
> [common]
> ; 是否保留留言和收藏
> keep_star_comment = false
> ```

不保留是不是改成ture呢?

**Comment by kessil** [comment]
@lmaisui 默认false不保留，这是后来加的配置
